let page=1,perPage=24,activeCategory="",dealsOnly=false,cart=JSON.parse(localStorage.getItem("neonCart")||"{}"),wishlist=new Set(JSON.parse(localStorage.getItem("neonWishlist")||"[]"));
const icons={"Tech":"⚡","Fashion":"✦","Shoes":"◈","Bags":"▣","Home":"⌂","Beauty":"✿","Electronics":"◉","Sports":"◇","Jewelry":"◆","Kids":"★","Kitchen":"♨","Travel":"✈"};
const $=id=>document.getElementById(id);
function init(){let cats=[...new Set(PRODUCTS.map(p=>p.category))];$("categoryStrip").innerHTML='<button onclick="filterCategory(\'\')" class="active">All</button>'+cats.map(c=>`<button onclick="filterCategory('${c}')">${icons[c]} ${c}</button>`).join("");$("categoryFilter").innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join("");updateCart();applyFilters()}
function filtered(){let q=$("searchInput").value.trim().toLowerCase(),max=+$("priceFilter").value,cat=$("categoryFilter").value||activeCategory;let a=PRODUCTS.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))&&p.price<=max&&(!cat||p.category===cat)&&(!dealsOnly||p.oldPrice>p.price*1.1));let s=$("sort").value;if(s==="low")a.sort((x,y)=>x.price-y.price);if(s==="high")a.sort((x,y)=>y.price-x.price);if(s==="rating")a.sort((x,y)=>y.rating-x.rating);if(s==="new")a.sort((x,y)=>y.id-x.id);return a}
function applyFilters(){page=1;let a=filtered(),start=(page-1)*perPage;$("resultInfo").textContent=`${a.length} products${activeCategory?" • "+activeCategory:""}`;$("productGrid").innerHTML=a.slice(start,start+perPage).map(card).join("")||'<div class="empty" style="grid-column:1/-1">No products found. Try another search or filter.</div>';renderPages(a.length)}
function card(p){return `<article class="product"><div class="product-media"><span class="badge ${p.badge==="HOT"?"hot":""}">${p.badge||"LUXE"}</span><button class="heart" onclick="toggleWish(${p.id})">${wishlist.has(p.id)?"♥":"♡"}</button><div class="product-art">${icons[p.category]||"✦"}</div></div><div class="product-info"><span class="product-cat">${p.category}</span><h3>${p.name}</h3><div class="stars">★★★★★ <span class="rating">${p.rating} (${p.reviews})</span></div><div class="price-row"><div><span class="price">$${p.price.toFixed(2)}</span> <span class="old">$${p.oldPrice.toFixed(2)}</span></div></div><button class="add" onclick="addCart(${p.id})">Add to cart</button><button class="add" style="background:transparent;border-color:#263142;color:#cbd5e1" onclick="viewProduct(${p.id})">Quick view</button></div></article>`}
function renderPages(n){let pages=Math.max(1,Math.ceil(n/perPage));$("pagination").innerHTML=Array.from({length:Math.min(pages,8)},(_,i)=>`<button class="${i+1===page?"active":""}" onclick="gotoPage(${i+1})">${i+1}</button>`).join("")}
function gotoPage(n){page=n;let a=filtered();$("productGrid").innerHTML=a.slice((page-1)*perPage,page*perPage).map(card).join("");renderPages(a.length);scrollToShop()}
function filterCategory(c){activeCategory=c;$("categoryFilter").value=c;document.querySelectorAll(".category-strip button").forEach(b=>b.classList.toggle("active",b.textContent.includes(c)||(c===""&&b.textContent.includes("All"))));applyFilters();scrollToShop()}
function clearSearch(){$("searchInput").value="";applyFilters()}
function resetFilters(){activeCategory="";$("categoryFilter").value="";$("priceFilter").value=1900;$("priceVal").textContent="$1900";$("sort").value="featured";dealsOnly=false;clearSearch()}
function toggleFilters(){$("filters").classList.toggle("open")}
function scrollToShop(){document.getElementById("shop").scrollIntoView({behavior:"smooth"})}
function showHome(){location.hash="";window.scrollTo({top:0,behavior:"smooth"});resetFilters()}
function showDeals(){dealsOnly=true;activeCategory="";$("categoryFilter").value="";applyFilters();scrollToShop()}
function save(){localStorage.setItem("neonCart",JSON.stringify(cart));localStorage.setItem("neonWishlist",JSON.stringify([...wishlist]))}
function addCart(id){cart[id]=(cart[id]||0)+1;save();updateCart();toast("Added to cart")}
function updateCart(){let n=Object.values(cart).reduce((a,b)=>a+b,0);$("cartCount").textContent=n}
function toggleWish(id){wishlist.has(id)?wishlist.delete(id):wishlist.add(id);save();applyFilters();toast(wishlist.has(id)?"Saved to wishlist":"Removed from wishlist")}
function cartItems(){return Object.entries(cart).map(([id,q])=>({p:PRODUCTS.find(x=>x.id==id),q})).filter(x=>x.p)}
function openCart(){let items=cartItems(),total=items.reduce((s,x)=>s+x.p.price*x.q,0);$("modalContent").innerHTML=`<p class="eyebrow">YOUR BAG</p><h2>Shopping cart</h2>${items.length?items.map(x=>`<div class="cart-line"><div class="cart-thumb">${icons[x.p.category]}</div><main><b>${x.p.name}</b><div>$${x.p.price.toFixed(2)}</div><div class="qty"><button onclick="changeQty(${x.p.id},-1)">−</button>${x.q}<button onclick="changeQty(${x.p.id},1)">+</button><button onclick="removeCart(${x.p.id})">Remove</button></div></main></div>`).join(""):`<div class="empty">Your cart is empty.</div>`}<h3>Total: $${total.toFixed(2)}</h3>${items.length?`<button class="primary" style="width:100%" onclick="openCheckout()">Continue to checkout →</button>`:""}`;$("modal").classList.remove("hidden")}
function changeQty(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];save();updateCart();openCart()}
function removeCart(id){delete cart[id];save();updateCart();openCart()}
function openCheckout(){let total=cartItems().reduce((s,x)=>s+x.p.price*x.q,0);if(!total)return; $("modalContent").innerHTML=`<p class="eyebrow">SECURE CHECKOUT</p><h2>Complete your order</h2><div class="checkout-grid"><input placeholder="First name"><input placeholder="Last name"><input class="full" placeholder="Email address" type="email"><input class="full" placeholder="Delivery address"><input placeholder="City"><input placeholder="State / region"><input placeholder="Phone number"><select><option>Nigeria</option><option>Ghana</option><option>United Kingdom</option><option>United States</option></select></div><h3>Payment method</h3><div class="pay-options"><label><input type="radio" name="pay" checked> Card</label><label><input type="radio" name="pay"> Bank transfer</label><label><input type="radio" name="pay"> Wallet / mobile</label><label><input type="radio" name="pay"> Cash on delivery</label></div><p><b>Order total: $${total.toFixed(2)}</b></p><button class="primary" style="width:100%" onclick="placeOrder()">Place order</button><p style="font-size:11px;color:#77869a">Demo checkout UI. Connect a secure payment provider/backend before accepting real payments.</p>`}
function placeOrder(){cart={};save();updateCart();closeModal();toast("Order placed — demo confirmation")}
function viewProduct(id){let p=PRODUCTS.find(x=>x.id===id);$("modalContent").innerHTML=`<p class="eyebrow">${p.category}</p><h2>${p.name}</h2><div class="product-media" style="border-radius:15px"><div class="product-art">${icons[p.category]}</div></div><h2>$${p.price.toFixed(2)}</h2><p>★★★★★ ${p.rating} • ${p.reviews} reviews</p><p style="color:#aab5c6">A premium ${p.category.toLowerCase()} selection from NEON LUXE. Choose your favorite and add it to your cart.</p><button class="primary" onclick="addCart(${p.id});closeModal()">Add to cart</button>`;$("modal").classList.remove("hidden")}
function openAccount(){$("modalContent").innerHTML=`<p class="eyebrow">NEON LUXE</p><h2>Your account</h2><div class="checkout-grid"><input placeholder="Email address" type="email"><input placeholder="Password" type="password"></div><button class="primary" style="width:100%;margin-top:12px" onclick="toast('Account demo');closeModal()">Sign in</button><p style="color:#7d899b">Account authentication is a UI placeholder. Add your production auth service when ready.</p>`;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
function toggleMenu(){$("mobileMenu").classList.toggle("open")}
function subscribe(e){e.preventDefault();$("email").value="";toast("You're subscribed")}
function toast(msg){let t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
$("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});init();
